services:
  db:
    ports:
      - "5432:5432"
    container_name: postgresql_container
    env_file: ./.env
    image: postgres
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    volumes:
      - C:\Users\XY373VZ\OneDrive - EY\Desktop\ingdelsoftware\postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: backend_container
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_URL=jdbc:postgresql://db:5432/emotion_recognition
      - DB_USERNAME=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - AZURE_STORAGE_CONN_STRING=$AZURE_STORAGE_CONN_STRING
    depends_on:
      - db
    restart: always