services:
  db:
    ports:
      - "5432:5432"
    container_name: postgresql_container
    env_file: .env
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    # volumes:
    #   - ./backend/postgres_data:/var/lib/postgresql/data
    restart: always
    profiles:
      - core  # Core services profile
      - full  # Full stack profile
  backend:
    container_name: backend_container
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:sqlserver://emotion-recognition-db-server.database.windows.net:1433;database=emotion_recognition;user=politecnico@emotion-recognition-db-server;password=gabriele1!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - DB_USERNAME=politecnico@emotion-recognition-db-server
      - DB_PASSWORD=gabriele1!
      - AZURE_STORAGE_CONN_STRING=${AZURE_STORAGE_CONN_STRING}
      - AZURE_STORAGE_SAS_TOKEN=${AZURE_STORAGE_SAS_TOKEN}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - SECURITY_ISSUER=${SECURITY_ISSUER}
      - SECURITY_SECRET=${SECURITY_SECRET}
    depends_on:
      - db
    restart: always
    profiles:
      - core  # Core services profile
      - full  # Full stack profile
      - backend  # Backend profile

  video-classifier:
    container_name: video_classifier_container
    build:
      context: ./video_classifier
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    profiles:
      - ml  # Machine Learning profile
      - full  # Full stack profile

volumes:
  postgres_data:
    driver: local